modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="DemSum"
description='''
Unofficial compatibility patch that lets Touhou Little Maid and MaidsoulKitchen recognize Sophisticated Storage and Sophisticated Backpacks block containers.

非官方兼容补丁，让 Touhou Little Maid 和 MaidsoulKitchen 能识别 Sophisticated Storage 与 Sophisticated Backpacks 的方块容器。
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="touhou_little_maid"
type="required"
versionRange="[1.3.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="maidsoulkitchen"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sophisticatedstorage"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sophisticatedbackpacks"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
